### PR TITLE
Add custom CSS option

### PR DESCRIPTION
**Pull request by Gabe-Mitnick**
I wanted to add some custom CSS to the controller (tweaking colors, padding, font, corner radius, etc.). I tried using Stylus, which injects custom CSS into webpages, but it seems like Stylus styles can't reach VSC's shadow DOM or something. This PR adds a text field to the add-on's settings page where they can enter custom CSS like
```
#controller {
    background-color: blue;
}
```
and it will be injected into the controller's shadow tree. Let me know if there's anything I should change, like edits to the setting description "Custom CSS to style the controller" to make it less confusing to users who don't know what CSS is.

### CODE REVIEW

**Comment by Gabe-Mitnick** [comment]
Hi @magnus-ISU, are you still maintaining this project?

**Comment by magnus-ISU** [comment]
I think I could implement that easily... I haven't looked at the code for over a year though

**Comment by magnus-ISU** [comment]
Oh it's a PR. I'll look at it when I get back to my computer

**Comment by Gabe-Mitnick** [comment]
@magnus-ISU pinging you again about this PR :)

**Comment by magnus-ISU** [comment]
Sorry for taking so long. I was procrastinating wanting to test it. Good PR, I'm glad the changes were so easy to make as it means all the work I did in refactoring igrigorik's settings page was worth it.

I also updated to manifest v3 now so I will probably be able to release on chromium too

**Pull request merged**
