### PR TITLE
Simplified code, improved consistency

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
Also fixed blinding white text in dark mode :)

### CODE REVIEW

**Comment by magnus-ISU** [comment]
Thanks, I've not written any CSS for months so mine was a mess.

**Comment by Gitoffthelawn** [comment]
No problem.  I've written over 20K lines of CSS since the pandemic started.  8-)

**Comment by Gitoffthelawn** [comment]
BTW, I always use `rgba(r, g, b, a)` syntax, but the code currently uses the old `rgba(r g b / a)` syntax.  Do you have a preference?

**Comment by magnus-ISU** [comment]
The former makes much more sense to me.

**Pull request merged**
